version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@aws-amplify/cli"
    versions:
    - 4.41.2
    - 4.44.2
    - 4.45.2
    - 4.48.0
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.11
    - 2.32.3
    - 2.32.8
    - 2.32.9
  - dependency-name: typescript
    versions:
    - 4.1.2
    - 4.1.3
    - 4.2.2
    - 4.2.3
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
    - 2.9.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: husky
    versions:
    - 4.3.7
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
